const BLOCKED_MODEL_IDS: Set<string> = new Set([
  // freight train
  'freightcar2',
  'metrotrain',
  'freightcont2',
  'freightcar',
  'tankercar',
  'freight2',
  'freight',
  'freighttrain',
  'freightcont1',
  'freightgrain',
  // truck trailers
  'freighttrailer',
  'tanker2',
  'docktrailer',
  'proptrailer',
  'graintrailer',
  'tvtrailer',
  'tr4',
  'tr2',
  'trflat',
  'trailers',
  'trailerlogs',
  'tvtrailer2',
  'tr3',
  'trailersmall',
  'trailers2',
  'trailers3',
  'raketrailer',
  'tanker',
  'trailers4',
  'trailers5',
  'boattrailer3',
  'boattrailer2',
  'boattrailer',
  'baletrailer',
  'armytrailer',
  'armytanker',
  'armytrailer2',
  'trailersmall2'
]);

export default BLOCKED_MODEL_IDS;
